## [教學目標]
學習 sklearn 中，各種評估指標的使用與意義

## [範例重點]
注意觀察各指標的數值範圍，以及輸入函數中的資料格式

In [2]:
from sklearn import metrics, datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
from matplotlib.pylab import rcParams
import numpy as np
%matplotlib inline

## 回歸問題
常見的評估指標有
- MAE
- MSE
- R-square

我們隨機生成(X, y)資料，然後使用線性回歸模型做預測，再使用 MAE, MSE, R-square 評估

In [4]:
X, y = datasets.make_regression(n_features=1, random_state=42, noise=4) # 生成資料

In [7]:
list(zip(X, y))[:5]

[(array([0.93128012]), 43.63556589773524),
 (array([0.08704707]), -1.8460438194196604),
 (array([-1.05771093]), -40.45736755632311),
 (array([0.31424733]), 12.080914854586563),
 (array([-0.47917424]), -19.09610685220991)]

In [8]:
model = LinearRegression() # 建立回歸模型
model.fit(X, y) # 將資料放進模型訓練
prediction = model.predict(X) # 進行預測

In [10]:
list(zip(prediction, y))[:5]

[(40.343021437608776, 43.63556589773524),
 (4.193360520128914, -1.8460438194196604),
 (-44.824636806675464, -40.45736755632311),
 (13.921968643595607, 12.080914854586563),
 (-20.051968655128597, -19.09610685220991)]

In [11]:
mae = metrics.mean_absolute_error(prediction, y) # 使用 MAE 評估
mse = metrics.mean_squared_error(prediction, y) # 使用 MSE 評估
r2 = metrics.r2_score(prediction, y) # 使用 r-square 評估
print("MAE: ", mae)
print("MSE: ", mse)
print("R-square: ", r2)

MAE:  2.8417972525655664
MSE:  12.488680067398233
R-square:  0.9916581036260311


## 分類問題
常見的評估指標有
- AUC
- F1-Score (Precision, Recall)

In [12]:
cancer = datasets.load_breast_cancer() # 我們使用 sklearn 內含的乳癌資料集
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=50, random_state=0)

In [17]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [21]:
import pandas as pd
df = pd.DataFrame(data=X_test, columns=cancer.feature_names)
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        13.40         20.52           88.64      556.7          0.11060   
1        13.21         25.25           84.10      537.9          0.08791   
2        14.02         15.66           89.59      606.5          0.07966   
3        14.26         18.17           91.22      633.1          0.06576   
4        13.03         18.42           82.61      523.8          0.08983   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.14690         0.14450              0.08172         0.2116   
1           0.05205         0.02772              0.02068         0.1619   
2           0.05581         0.02087              0.02652         0.1589   
3           0.05220         0.02475              0.01374         0.1635   
4           0.03766         0.02562              0.02923         0.1467   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07325  ...         16.41          29.66           113.30   
1                 0.05584  ...         14.35          34.23            91.29   
2                 0.05586  ...         14.91          19.31            96.53   
3                 0.05586  ...         16.22          25.26           105.80   
4                 0.05863  ...         13.30          22.81            84.46   

   worst area  worst smoothness  worst compactness  worst concavity  \
0       844.4           0.15740            0.38560          0.51060   
1       632.9           0.12890            0.10630          0.13900   
2       688.9           0.10340            0.10170          0.06260   
3       819.7           0.09445            0.21670          0.15650   
4       545.9           0.09701            0.04619          0.04833   

   worst concave points  worst symmetry  worst fractal dimension  
0               0.20510          0.3585                  0.11090  
1               0.06005          0.2444                  0.06788  
2               0.08216          0.2136                  0.06710  
3               0.07530          0.2636                  0.07676  
4               0.05013          0.1987                  0.06169  

[5 rows x 30 columns]

In [5]:
print(y_test) # 測試集中的 label

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 1 0 1 1 1 0]


In [22]:
y_pred = np.random.random((50,)) # 我們先隨機生成 50 筆預測值，範圍都在 0~1 之間，代表機率值

In [23]:
print(y_pred)

[0.23684017 0.2479067  0.79433632 0.01501469 0.02645124 0.35332628
 0.12596529 0.941679   0.85466422 0.39828187 0.64628535 0.68657168
 0.94038204 0.9919674  0.60746926 0.78824815 0.58571598 0.60517026
 0.38747992 0.47108675 0.37924112 0.25749668 0.9468824  0.53679178
 0.70987824 0.3988594  0.77950243 0.03090789 0.57454546 0.77582278
 0.72855984 0.72455107 0.51240819 0.94798389 0.4355624  0.88498617
 0.26251181 0.30678045 0.63584284 0.4313346  0.18559783 0.29452085
 0.92420423 0.99617989 0.58768082 0.79417684 0.01383056 0.99039223
 0.37028655 0.8860495 ]


### AUC

In [24]:
auc = metrics.roc_auc_score(y_test, y_pred) # 使用 roc_auc_score 來評估。 **這邊特別注意 y_pred 必須要放機率值進去!**
print("AUC: ", auc) # 得到結果約 0.5，與亂猜的結果相近，因為我們的預測值是用隨機生成的

AUC:  0.5008488964346349


## F1-Score

In [25]:
threshold = 0.5 # 設 0.5 為判斷門檻
y_pred_binarized = np.where(y_pred>threshold, 1, 0) # 使用 np.where 函數, 將 y_pred > 0.5 的值變為 1，小於 0.5 的為 0

In [26]:
f1 = metrics.f1_score(y_test, y_pred_binarized) # 使用 F1-Score 評估
precision = metrics.precision_score(y_test, y_pred_binarized) # 使用 Precision 評估
recall  = metrics.recall_score(y_test, y_pred_binarized) # 使用 recall 評估
print("F1-Score: ", f1) 
print("Precision: ", precision)
print("Recall: ", recall)

F1-Score:  0.6333333333333333
Precision:  0.6551724137931034
Recall:  0.6129032258064516


## [作業重點]
了解 F1-score 的公式意義，並試著理解程式碼

## 作業
請參考 F1-score 的公式與[原始碼](https://github.com/scikit-learn/scikit-learn/blob/bac89c2/sklearn/metrics/classification.py#L620)，試著寫出 F2-Score 的計算函數